# Generated by Django 3.1.13 on 2021-08-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('-name',),
            },
        ),
        migrations.AlterModelOptions(
            name='pwa',
            options={'ordering': ('-name',), 'verbose_name': 'Pwa', 'verbose_name_plural': 'Pwas'},
        ),
        migrations.AddField(
            model_name='pwa',
            name='tags',
            field=models.ManyToManyField(related_name='pwaTags', to='pwas.Tag'),
        ),
    ]
