# Generated by Django 3.1.13 on 2021-08-13 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0003_auto_20210813_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwa',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='pwa_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PwaRating', to='pwas.pwa'),
            preserve_default=False,
        ),
    ]
