# Generated by Django 3.1.13 on 2021-08-13 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0004_auto_20210813_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='pwa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pwas.pwa'),
        ),
    ]
