# Generated by Django 3.1.13 on 2021-08-13 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pwas', '0005_auto_20210813_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwa',
            name='launches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('pwa_id', 'owner')},
        ),
    ]
