# Generated by Django 3.1.13 on 2021-08-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20210807_2236'),
        ('pwas', '0007_auto_20210813_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='pwa',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='pwas.Tag'),
        ),
    ]
