# Generated by Django 3.1.13 on 2021-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0008_auto_20210813_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwa',
            name='short_description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pwa',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pwa',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
