# Generated by Django 3.1.13 on 2021-08-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0009_auto_20210813_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwa',
            name='icon_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
