# Generated by Django 3.1.13 on 2021-08-14 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pwas', '0010_pwa_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwa',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='pwa',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='pwa',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pwa',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pwa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pwa',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwa_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pwa',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pwa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pwa',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwa_updator', to=settings.AUTH_USER_MODEL),
        ),
    ]
