# Generated by Django 3.1.13 on 2021-08-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0013_pwaanalytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pwaanalytics',
            options={'verbose_name': 'Pwa Analytics', 'verbose_name_plural': 'Pwa Analytics'},
        ),
        migrations.RemoveField(
            model_name='pwa',
            name='tags',
        ),
        migrations.AddField(
            model_name='pwa',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='pwas.tag'),
        ),
    ]
