# Generated by Django 3.1.13 on 2021-08-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0017_auto_20210814_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwaanalytics',
            name='pwa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pwa_analytics', to='pwas.pwa'),
            preserve_default=False,
        ),
    ]
