# Generated by Django 3.1.13 on 2021-08-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0018_auto_20210814_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pwa',
            options={'ordering': ('name',), 'verbose_name': 'Pwa', 'verbose_name_plural': 'Pwas'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('value',), 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
