# Generated by Django 3.1.13 on 2021-08-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0021_favoritepwa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pwa',
            old_name='icon_url',
            new_name='image_url',
        ),
    ]
