# Generated by Django 3.1.13 on 2021-08-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0022_auto_20210815_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwaScreenShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image_url', models.CharField(max_length=250)),
                ('pwa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwa_screenshots', to='pwas.pwa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
