# Generated by Django 3.1.13 on 2021-08-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0023_pwascreenshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pwascreenshots',
            options={'verbose_name': 'Pwa Screenshots', 'verbose_name_plural': 'Pwa Screenshots'},
        ),
    ]
