# Generated by Django 3.1.13 on 2021-08-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0024_auto_20210815_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwascreenshots',
            name='caption',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
