# Generated by Django 3.1.13 on 2021-08-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0025_pwascreenshots_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwascreenshots',
            name='pwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwa_screenshots', to='pwas.pwa'),
        ),
    ]
