# Generated by Django 3.1.13 on 2021-08-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0026_auto_20210815_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PwaScreenShots',
            new_name='PwaScreenshot',
        ),
    ]
