# Generated by Django 3.1.13 on 2021-08-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0027_auto_20210815_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=350, null=True),
        ),
    ]
