# Generated by Django 3.1.13 on 2021-08-20 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0030_auto_20210820_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
