# Generated by Django 3.1.13 on 2021-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0030_auto_20210820_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwaanalytics',
            name='rating_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pwaanalytics',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
