# Generated by Django 3.1.13 on 2021-08-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0031_auto_20210821_1042'),
        ('pwas', '0031_auto_20210820_1542'),
    ]

    operations = [
    ]
