# Generated by Django 3.1.13 on 2021-08-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0031_auto_20210821_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('rating',), 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
    ]
