# Generated by Django 3.1.13 on 2021-08-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0031_auto_20210820_1542'),
        ('pwas', '0032_auto_20210821_1849'),
    ]

    operations = [
    ]
