# Generated by Django 3.1.13 on 2021-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0033_merge_20210821_1924'),
        ('pwas', '0032_merge_20210821_2039'),
    ]

    operations = [
    ]
