# Generated by Django 3.1.13 on 2021-08-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0035_auto_20210822_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwa',
            name='short_description',
        ),
    ]
