# Generated by Django 3.1.13 on 2021-08-22 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0036_remove_pwa_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='manifest_url',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
