# Generated by Django 3.1.13 on 2021-08-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0036_remove_pwa_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwaanalytics',
            name='rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
