# Generated by Django 3.1.13 on 2021-08-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0037_auto_20210822_1709'),
        ('pwas', '0037_auto_20210822_1537'),
    ]

    operations = [
    ]
