# Generated by Django 3.2.6 on 2021-08-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0038_merge_20210822_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwaanalytics',
            name='rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
