# Generated by Django 3.2.6 on 2021-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0039_alter_pwaanalytics_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwaanalytics',
            name='rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
