# Generated by Django 3.2.6 on 2021-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0042_alter_pwa_manifest_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='manifest_json',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
