# Generated by Django 3.2.6 on 2021-08-25 20:39

from django.db import migrations, models
import pwa_store_backend.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0043_alter_pwa_manifest_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='manifest_json',
            field=models.TextField(max_length=5000, null=True, validators=[pwa_store_backend.utils.validators.validate_json]),
        ),
    ]
