# Generated by Django 3.2.6 on 2021-08-28 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0044_alter_pwa_manifest_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='url',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
