# Generated by Django 3.2.6 on 2021-08-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0046_alter_pwa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwa',
            name='manifest_json',
        ),
    ]
