# Generated by Django 3.2.6 on 2021-08-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0047_remove_pwa_manifest_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwa',
            name='manifest_json',
            field=models.JSONField(null=True),
        ),
    ]
