# Generated by Django 3.2.6 on 2021-08-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0049_alter_pwa_manifest_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='manifest_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
