# Generated by Django 3.2.6 on 2021-08-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0052_alter_pwa_manifest_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritePwa',
        ),
    ]
