# Generated by Django 3.2.6 on 2021-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0053_delete_favoritepwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='manifest_json',
            field=models.JSONField(default=dict),
        ),
    ]
