# Generated by Django 3.2.6 on 2021-09-04 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0054_alter_pwa_manifest_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='manifest_url',
            field=models.CharField(max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
