# Generated by Django 3.2.6 on 2021-09-04 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwas', '0055_alter_pwa_manifest_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwa',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
