# Generated by Django 3.1.13 on 2021-08-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'dark')], default='light', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='modes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usersetting'),
        ),
    ]
