# Generated by Django 3.1.13 on 2021-08-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210815_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='modes',
            new_name='setting',
        ),
    ]
