# Generated by Django 3.1.13 on 2021-08-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210815_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usersetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
