# Generated by Django 3.1.13 on 2021-08-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_contributors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('-name',), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
