# Generated by Django 3.1.13 on 2021-08-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_auto_20210814_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contributors',
        ),
        migrations.AddField(
            model_name='organization',
            name='contributors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizationContributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
