# Generated by Django 3.1.13 on 2021-08-14 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_auto_20210814_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contributors',
        ),
        migrations.AddField(
            model_name='organization',
            name='contributors',
            field=models.ManyToManyField(related_name='organizationContributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
